- src/context.cairo
- src/instructions.cairo
- src/instructions/stop_and_arithmetic_operations.cairo
> 🚧 init stop and arithmetic operations

- .github/workflows/test.yml
- Makefile
- src/evm.cairo
- src/instructions.cairo
- 🚧 init stop and arithmetic operations
- 🚧 init structure
- ⬆️ latest Cairo 1 version
-
-
-
> Init repository structure

- .github/workflows/test.yml
- Makefile
- src/context.cairo
- src/instructions.cairo
- src/stack.cairo
- src/tests.cairo
- src/tests/kakarot_test.cairo
- src/tests/stack_test.cairo
- src/utils.cairo
Array-based stack
Dict-based, mutable U256 Stack
-
-
-
> feat: mutable stack

- .github/workflows/test.yml
- src/context.cairo
- src/instructions.cairo
- src/instructions/duplication_operations.cairo
- src/instructions/exchange_operations.cairo
- src/instructions/logging_operations.cairo
- src/instructions/push_operations.cairo
- src/stack.cairo
- src/tests/kakarot_test.cairo
- src/tests/stack_test.cairo
- src/utils.cairo
Fixed some bugs due to prior compiler versions.
Cleaned the code with the type inference features.
-
-
-
> chore: bump to 1.0.0-rc0

- .tool-versions
- src/context.cairo
- src/errors.cairo
- src/evm.cairo
- src/instructions.cairo
- src/lib.cairo
- src/memory.cairo
- src/model.cairo
- src/stack.cairo
- src/tests.cairo
- src/tests/test_execution_context.cairo
- src/tests/test_kakarot.cairo
- src/tests/utils.cairo
- src/utils/helpers.cairo
Skeleton of a first draft of the ExecutionContext.
This PR doesn't look into any optimisation and just provides an implementation with the bare minimum so that we can continue working towards the first opcode. Once we will have a clearer view of the requirements after trying multiple things with Cairo 1, we will think about the refactoring and have a final version of it.
Issue Number: #43 
-
-
-
> feat: first execution context skeleton

- src/instructions/stop_and_arithmetic_operations.cairo
- src/tests/test_instructions/test_stop_and_arithmetic_operations.cairo
- src/tests/test_kakarot.cairo
First arithmetic opcodes. Created issues for other opcodes that require more work in other parts.
Issue Number: Closes #24 Closes #20 Closes #21 Closes #22 Closes #3
- ADD, SUB, DIV, MOD, ADDMOD opcodes
- Their respective tests
-
> feat: arithmetic opcodes

- src/instructions/stop_and_arithmetic_operations.cairo
- src/tests/test_instructions/test_stop_and_arithmetic_operations.cairo
- src/tests/test_utils/test_u256_signed_math.cairo
Issue Number: Closes #23 
- Implements the sdiv opcode
-
-
Based on #68
> feat: 0x05 sdiv

- docs/CONTRIBUTING.md
> doc: add migration markdown doc

- src/memory.cairo
- src/tests/test_memory.cairo
Issue Number: Closes #84 
- Removed `_` prefixes for internal functions. Either moved them to an `internal` module, or renamed them without this leading underscore.
-
-
> chore: remove _ prefixes

- CHANGELOG.md
- src/instructions/stop_and_arithmetic_operations.cairo
- src/tests/test_instructions/test_stop_and_arithmetic_operations.cairo
Issue Number: Closes #94 
- Implements 0x07-SMOD opcode
-
-
> feat: 0x07-smod

- CHANGELOG.md
- src/instructions/comparison_operations.cairo
- src/tests/test_instructions/test_comparison_operations.cairo
> feat: implement and

- CHANGELOG.md
- src/instructions/comparison_operations.cairo
- src/tests/test_instructions/test_comparison_operations.cairo
> feat: implement not

- CHANGELOG.md
- src/instructions.cairo
- src/instructions/comparison_operations.cairo
- src/instructions/duplication_operations.cairo
- src/interpreter.cairo
- src/tests/test_instructions.cairo
- src/tests/test_instructions/test_duplication_operations.cairo
DUP operations are not implemented
fix #98 
fix #99
fix #101 
fix #102
fix #103
fix #104
fix #105
fix #106 
fix #107 
fix #108
fix #109 
fix #110
fix #111
fix #112
fix  #113
fix  #114 
sorry for spamming all this issues, but doing this will auto close those issues so we wouldn't need to close them manually.
> feat: implement DUP1 to DUP16

- CHANGELOG.md
- src/instructions/comparison_operations.cairo
- src/tests/test_instructions/test_comparison_operations.cairo
- src/tests/test_stack.cairo
> feat: impl byte

- Makefile
- README.md
- Scarb.toml
Migrating to scarb workspaces makes it impossible to run scripts defined in the top-level virtual workspace. This makes it a bit harder to handle custom scripts that are not bound to a specific package, therefore I propose to remove the scarb scripts and replace them with a Makefile.
-
-
-
> feat: add makefile

- .github/workflows/gas_reports.yml
- .github/workflows/gas_snapshot.yml
- .github/workflows/test.yml
- .tool-versions
> chore: bump scarb

- CHANGELOG.md
- crates/evm/src/errors.cairo
- crates/evm/src/instructions.cairo
- crates/evm/src/instructions/block_information.cairo
- crates/evm/src/interpreter.cairo
- crates/evm/src/tests/test_instructions.cairo
- crates/evm/src/tests/test_instructions/test_block_information.cairo
Fixes #151 
Resolves: #
- Non
Timestamp opcode
> feat(block_information): add  timestamp opcode

- CHANGELOG.md
- crates/evm/src/instructions.cairo
- crates/evm/src/instructions/environmental_information.cairo
- crates/evm/src/interpreter.cairo
- crates/evm/src/tests/test_instructions.cairo
- crates/evm/src/tests/test_instructions/test_environment_information.cairo
- crates/utils/src/helpers.cairo
Resolves: #116 
- implements ADDRESS opcode
- add tests for the same
> feat(environmental_information): implement ADDRESS opcode

- crates/evm/src/context.cairo
- crates/evm/src/instructions/block_information.cairo
- crates/evm/src/tests/test_instructions/test_block_information.cairo
> feat(evm): add basefee opcode

- crates/evm/src/context.cairo
- crates/evm/src/instructions/block_information.cairo
- crates/evm/src/tests/test_instructions/test_block_information.cairo
> feat(evm): add gaslimit opcode

- crates/evm/src/instructions/comparison_operations.cairo
- crates/evm/src/instructions/duplication_operations.cairo
- crates/evm/src/instructions/stop_and_arithmetic_operations.cairo
- crates/evm/src/interpreter.cairo
Resolves: #190 
- simplifies the returns
> refactor: simplify returns

- crates/evm/src/instructions/comparison_operations.cairo
- crates/evm/src/tests/test_instructions/test_comparison_operations.cairo
Not implemented
Resolves: #6 
Implements opcode
> feat: implement 0x11 - GT opcode

- crates/evm/src/tests/test_execution_context.cairo
> revert unintended changes

- crates/evm/src/context.cairo
- crates/evm/src/memory.cairo
- crates/evm/src/stack.cairo
- crates/evm/src/tests/test_stack.cairo
- crates/utils/src/lib.cairo
- crates/utils/src/traits.cairo
- scripts/compare_snapshot.py
> feat: derive default trait

- crates/evm/src/context.cairo
- crates/evm/src/execution.cairo
- crates/evm/src/tests/test_instructions/test_comparison_operations.cairo
- crates/evm/src/tests/test_utils.cairo
Changing all returned_data to return_data for execution context.
Resolves: #267
-
-
-
> Fix returned_data to return_data

- crates/utils/src/helpers.cairo
> [doc] Replace u128 by u256

- crates/evm/src/instructions/memory_operations.cairo
- crates/evm/src/tests/test_instructions/test_memory_operations.cairo
POP opcode implementation,
Resolves: #262
-
-
-
> feat: implement 0x50 - POP Opcode

- crates/utils/src/helpers.cairo
- crates/utils/src/tests/test_helpers.cairo
Add a helper method that clones a span and pads it with zeroes
Resolves: #
-
-
-
> feat: span pad end zeroes

- .github/workflows/gas_reports.yml
- scripts/compare_snapshot.py
- scripts/install_hook.sh
Snapshot CI not working
No error message when no GITHUB_TOKEN
CI & Error message
Removed the push hook as it is too slow
> Fix compare-snapshot script

- crates/evm/src/instructions/memory_operations.cairo
- crates/evm/src/memory.cairo
- crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> add msize opcode

- README.md
There are 2 types of github tokens. One of them gives errors in the gas snapshot script if you don't set it right.
Resolves: #
- Sending the dev that's running Kkrt for the first time, directly to where can he create the token. Just trying to make it easier :)
> Link to get Github token for .env

- crates/evm/src/instructions/environmental_information.cairo
- crates/evm/src/instructions/memory_operations.cairo
- crates/evm/src/instructions/system_operations.cairo
- crates/evm/src/stack.cairo
- crates/evm/src/tests/test_instructions/test_environment_information.cairo
> feat: implement pop_type methods and use them

- crates/evm/src/instructions/memory_operations.cairo
- crates/evm/src/memory.cairo
- crates/evm/src/tests/test_instructions/test_memory_operations.cairo
- crates/evm/src/tests/test_memory.cairo
Resolves: #288
- Removed memory gas cost calculations
-
-
> refactor: remove legacy gas calculations

- crates/evm/src/instructions/memory_operations.cairo
- crates/evm/src/tests/test_instructions/test_memory_operations.cairo
> feat: implement JUMP instruction

- crates/evm/src/instructions/memory_operations.cairo
Resolves: #260 
- added for clarity that its supposed to be an NO-OP
> feat: add comment for JUMPDEST opcode

- crates/evm/src/instructions/memory_operations.cairo
- crates/evm/src/tests/test_instructions/test_memory_operations.cairo
- docs/supported_opcodes.md
Resolves: #252 
- implement `JUMPI` opcode
- merge after #355
> feat: implement JUMPI instruction

- README.md
@Eikix  @enitrat 
it's not possible to delete a contributor with All contributors, and then add it again.
I dit it manually then, i made a PR yesterday that was accepted but i only modified the all-contributorssrc file . I actually had to also modify the README.md file , which i did in this PR. After that, all should be ok !*
sorry for the loss of time for such unimportant issue.
> Final name update

- .github/workflows/gas_reports.yml
- .github/workflows/gas_snapshot.yml
- scripts/compare_snapshot.py
Result is now displayed in the workflow summary section
Resolves: #
-
-
-
> ci: log result

- .trunk/.gitignore
- .trunk/configs/.isort.cfg
- .trunk/configs/.shellcheckrc
- .trunk/configs/.yamllint.yaml
- .trunk/configs/ruff.toml
- .trunk/trunk.yaml
- scripts/compare_snapshot.py
The script uses `print`.
Use a real `logger` instead.
> Replace print with logger in snapshot script

- .github/workflows/gas_reports.yml
- [w] Bugfix
Checked with @eni, this has never worked for failed PR.
Trying to split in two steps.
> Fix summary bis

- .devcontainer/devcontainer.json
Running devcontainer did not work.
Running devcontainer works.
> Dev: fix devcontainer

- crates/evm/src/instructions/sha3.cairo
- crates/evm/src/memory.cairo
- crates/evm/src/tests/test_execution_context.cairo
- crates/evm/src/tests/test_instructions/test_environment_information.cairo
- crates/evm/src/tests/test_instructions/test_memory_operations.cairo
- crates/evm/src/tests/test_instructions/test_sha3.cairo
- crates/evm/src/tests/test_memory.cairo
- docs/general/machine.md
Resolves: #370 
-
-
-
- [ x ] Yes
> feat: update memory with new active segment

- crates/evm/src/context.cairo
- crates/evm/src/instructions/environmental_information.cairo
- crates/evm/src/machine.cairo
- crates/evm/src/tests/test_execution_context.cairo
- crates/evm/src/tests/test_instructions/test_environment_information.cairo
- crates/evm/src/tests/test_utils.cairo
> feat: origin

- crates/evm/src/context.cairo
- crates/evm/src/interpreter.cairo
- crates/evm/src/machine.cairo
- crates/evm/src/storage_journal.cairo
Finalizes storage changes when
- Returning from a sub execution context => Finalize local changes into global changes
- Returning from the root context => Finalize local changes into global changes into starknet storage
Handles the reverting behavior of a subcontext by clearing local changes.
Resolves: #411
-
-
-
> feat: finalize storage changes

- crates/eoa/Scarb.toml
- crates/eoa/src/externally_owned_account.cairo
- crates/eoa/src/tests/test_externally_owned_account.cairo
- crates/evm/src/tests/test_utils.cairo
> refactor: update eoa

- crates/evm/src/tests/test_instructions/test_comparison_operations.cairo
- crates/utils/src/math.cairo
- crates/utils/src/num.cairo
- crates/utils/src/tests/test_math.cairo
Exponentiation uses a implementation which is $O(n)$, instead of fast powering which provides a $O(log(n))$ complexity (where n is the exponent of the Exponentiation).
Resolves: #184 
- Use fast powering for an exponent > 10.
> fix: exponential

- crates/evm/src/instructions/block_information.cairo
- crates/evm/src/instructions/memory_operations.cairo
- crates/evm/src/tests/test_instructions/test_block_information.cairo
- crates/evm/src/tests/test_instructions/test_memory_operations.cairo
- docs/supported_opcodes.md
- add new opcodes in the supported opcodes
- implement a next-best solution for prevrandao and gas
Resolves: #258  #153 
- prevrandao always returns 0
- gas always returns gas_limit()
-
> feat: add gas and randao

- crates/contracts/src/kakarot_core/kakarot.cairo
- crates/evm/src/model/eoa.cairo
- crates/evm/src/tests/test_model.cairo
- crates/evm/src/tests/test_model/test_contract_account.cairo
- crates/evm/src/tests/test_model/test_eoa.cairo
> refactor: eoa deployment

- crates/evm/src/instructions/memory_operations.cairo
- crates/evm/src/instructions/system_operations.cairo
- crates/evm/src/tests/test_instructions/test_memory_operations.cairo
- crates/evm/src/tests/test_utils.cairo
> fix: fix check if context is static in sstore, create, create2

- crates/contracts/src/tests/test_contract_account.cairo
- crates/contracts/src/tests/test_kakarot_core.cairo
- crates/contracts/src/tests/test_uninitialized_account.cairo
- crates/contracts/src/uninitialized_account/uninitialized_account.cairo
- crates/evm/src/tests/test_instructions/test_environment_information.cairo
- crates/evm/src/tests/test_instructions/test_system_operations.cairo
- crates/evm/src/tests/test_model/test_contract_account.cairo
- crates/evm/src/tests/test_model/test_eoa.cairo
> feat: account infinite token approval

- crates/evm/src/instructions/sha3.cairo
- crates/utils/src/errors.cairo
- crates/utils/src/eth_transaction.cairo
- crates/utils/src/helpers.cairo
- crates/utils/src/rlp.cairo
- crates/utils/src/tests.cairo
- crates/utils/src/tests/test_eth_transaction.cairo
Resolves: #407 
-  Add decoding of legacy transactions
> feat: add legacy transaction decoding

- crates/contracts/src/tests/test_contract_account.cairo
- crates/contracts/src/tests/test_kakarot_core.cairo
- crates/contracts/src/tests/test_uninitialized_account.cairo
- crates/contracts/src/tests/test_utils.cairo
- crates/evm/src/tests/test_execution.cairo
- crates/evm/src/tests/test_instructions/test_block_information.cairo
- crates/evm/src/tests/test_instructions/test_environment_information.cairo
- crates/evm/src/tests/test_instructions/test_memory_operations.cairo
- crates/evm/src/tests/test_instructions/test_system_operations.cairo
- crates/evm/src/tests/test_model.cairo
- crates/evm/src/tests/test_model/test_contract_account.cairo
- crates/evm/src/tests/test_model/test_eoa.cairo
- crates/evm/src/tests/test_state.cairo
Resolves: #509 
- Created `setup_contracts_for_testing` inside `crates::contracts::tests::test_utils`,
- Replaced the contracts deployment by a call to `setup_contracts_for_testing` when applicable,
- Removed unused imports in some tests
> dev: Refactor test contracts deployment

- docs/general/local_state.md
Resolves: #
- Add state sequence diagram
-
-
> docs: update state doc

- docs/general/contract_bytecode.md
Resolves: #
- Fix bytecode storage documentation to reflect the actual implementation in the codebase.
-
-
> docs: fix bytecode storage doc

- crates/utils/src/errors.cairo
- crates/utils/src/eth_transaction.cairo
- crates/utils/src/tests/test_eth_transaction.cairo
Transaction validation is not implemented.
Resolves: #523 
- The logic was transaction validation has been implemented.
> feat: implement eth transaction validate

- .trunk/trunk.yaml
- crates/evm/src/call_helpers.cairo
- crates/evm/src/instructions/system_operations.cairo
> fix: delegatecall caller

- crates/contracts/src/eoa.cairo
- crates/contracts/src/tests/test_eoa.cairo
- crates/evm/src/model/eoa.cairo
- crates/evm/src/tests/test_model/test_eoa.cairo
> feat: chain_id in eao

- crates/contracts/src/contract_account.cairo
- crates/contracts/src/eoa.cairo
- crates/contracts/src/tests/test_eoa.cairo
- crates/contracts/src/tests/test_kakarot_core.cairo
- crates/evm/src/create_helpers.cairo
- crates/evm/src/execution.cairo
- crates/evm/src/instructions/environmental_information.cairo
- crates/evm/src/instructions/system_operations.cairo
- crates/evm/src/model.cairo
- crates/evm/src/model/account.cairo
- crates/evm/src/model/contract_account.cairo
- crates/evm/src/model/eoa.cairo
- crates/evm/src/tests/test_execution_context.cairo
- crates/evm/src/tests/test_instructions/test_block_information.cairo
- crates/evm/src/tests/test_instructions/test_environment_information.cairo
- crates/evm/src/tests/test_instructions/test_memory_operations.cairo
- crates/evm/src/tests/test_instructions/test_system_operations.cairo
- crates/evm/src/tests/test_model.cairo
- crates/evm/src/tests/test_model/test_contract_account.cairo
- crates/evm/src/tests/test_state.cairo
- crates/evm/src/tests/test_utils.cairo
> feat: selfdestruct

- crates/contracts/src/contract_account.cairo
- crates/contracts/src/eoa.cairo
- crates/contracts/src/tests/test_eoa.cairo
- crates/contracts/src/tests/test_kakarot_core.cairo
- crates/evm/src/create_helpers.cairo
- crates/evm/src/execution.cairo
- crates/evm/src/instructions/environmental_information.cairo
- crates/evm/src/instructions/system_operations.cairo
- crates/evm/src/model.cairo
- crates/evm/src/model/account.cairo
- crates/evm/src/model/contract_account.cairo
- crates/evm/src/model/eoa.cairo
- crates/evm/src/tests/test_execution_context.cairo
- crates/evm/src/tests/test_instructions/test_block_information.cairo
- crates/evm/src/tests/test_instructions/test_environment_information.cairo
- crates/evm/src/tests/test_instructions/test_memory_operations.cairo
- crates/evm/src/tests/test_instructions/test_system_operations.cairo
- crates/evm/src/tests/test_model.cairo
- crates/evm/src/tests/test_model/test_contract_account.cairo
- crates/evm/src/tests/test_state.cairo
- crates/evm/src/tests/test_utils.cairo
Reverts kkrt-labs/kakarot-ssj#554
> Revert "feat: selfdestruct"

- crates/evm/src/instructions/system_operations.cairo
- crates/evm/src/tests/test_instructions/test_system_operations.cairo
callcode opcode isn't implemented.
Resolves: #395 
- callcode opcode is implemented
> feat: add callcode

- .github/workflows/gas_reports.yml
- .github/workflows/gas_snapshot.yml
- .github/workflows/test.yml
- .tool-versions
- Scarb.toml
- crates/contracts/src/tests/test_kakarot_core.cairo
- scripts/compute_starknet_address.ts
> chore: bump cairo to nigtly

- .all-contributorsrc
- README.md
Resolves: NA
- Added missing contributors using `all-contributors-cli`
> docs: Added missing contributors

- crates/evm/src/execution.cairo
- crates/evm/src/interpreter.cairo
- crates/evm/src/machine.cairo
- crates/evm/src/model.cairo
- crates/evm/src/state.cairo
- crates/evm/src/tests/test_execution.cairo
- crates/evm/src/tests/test_instructions/test_system_operations.cairo
- crates/evm/src/tests/test_machine.cairo
- crates/evm/src/tests/test_utils.cairo
Resolves: #574 
- implementing revert for EVM errors and REVERT opcode
-
-
> feat: revert-behavior

- crates/evm/src/context.cairo
- crates/evm/src/machine.cairo
> refactor: use box_snapshot

- .github/workflows/artifacts.yml
- .trunk/trunk.yaml
> build: contract artifacts

- crates/contracts/src/kakarot_core/kakarot.cairo
- crates/evm/src/call_helpers.cairo
- crates/evm/src/create_helpers.cairo
- crates/evm/src/model.cairo
- crates/evm/src/model/vm.cairo
- crates/evm/src/state.cairo
- crates/evm/src/tests/test_state.cairo
- crates/evm/src/tests/test_utils.cairo
- crates/utils/src/helpers.cairo
- crates/utils/src/lib.cairo
- crates/utils/src/set.cairo
- crates/utils/src/tests.cairo
- crates/utils/src/tests/test_set.cairo
Implements an array-based `Set` data structure (used for AccessList)
Resolves: #
-
-
-
> feat: set data structure

- .trunk/trunk.yaml
- crates/contracts/src/eoa.cairo
- crates/contracts/src/kakarot_core/kakarot.cairo
- crates/evm/src/call_helpers.cairo
The higher limit for precompiles address is 0x10.
Resolves: #NA
The limit is updated to 10.
> fix: precompile contracts limit address

- crates/evm/src/call_helpers.cairo
> fix: is_precompile

- crates/contracts/src/eoa.cairo
- crates/contracts/src/tests/test_eoa.cairo
The current `TransactionExecuted` event is not consistent with KKRT-0 codebase
Resolves: #652 
- `TransactionExecuted` event is consistent with KKRT-0 codebase
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/653)
> feat: make TransactionEmitted event consistent

- crates/contracts/src/kakarot_core/kakarot.cairo
- crates/evm/src/gas.cairo
- crates/evm/src/tests/test_gas.cairo
- crates/utils/src/eth_transaction.cairo
- crates/utils/src/set.cairo
- Access Lists are not supported
Resolves: #617 
- Access Lists are supported
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/660)
> feat: add support for access list

- crates/evm/src/create_helpers.cairo
Resolves: #655 
- Compute charge and reimburse create messages gas
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/661)
> feat(gas): charge-create-message-gas

- crates/contracts/src/kakarot_core/kakarot.cairo
- crates/contracts/src/tests/test_utils.cairo
- crates/evm/src/errors.cairo
- crates/evm/src/instructions/block_information.cairo
- crates/evm/src/instructions/memory_operations.cairo
- crates/evm/src/model/account.cairo
- crates/evm/src/model/contract_account.cairo
- crates/evm/src/state.cairo
- crates/evm/src/tests/test_instructions/test_block_information.cairo
- crates/evm/src/tests/test_instructions/test_environment_information.cairo
- crates/evm/src/tests/test_instructions/test_memory_operations.cairo
- crates/evm/src/tests/test_instructions/test_system_operations.cairo
- crates/evm/src/tests/test_model.cairo
- crates/evm/src/tests/test_model/test_contract_account.cairo
- crates/evm/src/tests/test_state.cairo
- crates/evm/src/tests/test_utils.cairo
Resolves: #669
- Removed SN-syscalls related errors
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/670)
> feat: remove SN-syscall related errors

- .github/workflows/ef_tests.yml
Resolves: #
This integrates ef-tests to the kakarot ssj CI.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/668)
> feat: add ef-tests to SSJ

- .github/workflows/ef_tests.yml
- .trunk/trunk.yaml
- crates/evm/src/memory.cairo
As of now, we have to create a new pull request to run ef-tests to find out how many new tests we pass.
Resolves: #679 
- allows to manually trigger running of ef-tests of all tests 
- automatically generates a new file and uploads it as artifact
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/678)
> feat: add blockchain-tests-skip generation file to CI

- .github/workflows/ef_tests.yml
- .trunk/trunk.yaml
This should fix manual trigger of ef-tests.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/681)
> fix: fix manual trigger of ef-tests run!

- crates/utils/src/helpers.cairo
- scripts/compare_snapshot.py
Resolves: #
- Optimizes the u32 from_bytes by using hardcoded values instead of bitshift. Eventually, all of these can be optimized
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/684)
> dev: optimize from_bytes u32

- .tool-versions
- crates/contracts/src/eoa.cairo
- crates/contracts/src/kakarot_core/kakarot.cairo
- crates/contracts/src/tests/test_kakarot_core.cairo
- crates/contracts/src/tests/test_utils.cairo
- crates/evm/src/instructions/memory_operations.cairo
- crates/evm/src/instructions/system_operations.cairo
- crates/evm/src/model.cairo
- crates/evm/src/model/account.cairo
- crates/evm/src/state.cairo
- crates/utils/src/address.cairo
- crates/utils/src/eth_transaction.cairo
- crates/utils/src/fmt.cairo
- crates/utils/src/helpers.cairo
- crates/utils/src/tests/test_helpers.cairo
- crates/utils/src/traits.cairo
Resolves: #
- fixed some TODOs related to compiler bugs
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/688)
> fix: compiler issues

- crates/evm/src/gas.cairo
- crates/evm/src/instructions/stop_and_arithmetic_operations.cairo
Resolves: #687 
- Dynamic accounting of gas for the EXP opcode
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/689)
> feat: dynamic exp gas

- crates/evm/src/instructions/system_operations.cairo
Resolves: #
- Fix an issue in selfdestruct where gas was charged twice.
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/690)
> fix: selfdestruct double gas charge

- crates/contracts/src/kakarot_core/kakarot.cairo
- crates/contracts/src/tests/test_utils.cairo
- crates/evm/src/call_helpers.cairo
- crates/evm/src/create_helpers.cairo
- crates/evm/src/instructions/environmental_information.cairo
- crates/evm/src/interpreter.cairo
- crates/evm/src/model.cairo
- crates/evm/src/tests/test_state.cairo
Removes print statements, as they're quite gas consuming and they make some EF-tests reach OOG 😢
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/693)
> chore: remove prints

- .github/workflows/ef_tests.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/695)
> Fix ef test step not failing

- crates/evm/src/gas.cairo
- crates/evm/src/tests/test_gas.cairo
fix wrong memory cost calculation
Resolves: #700 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/701)
> bug: fix_memory_cost_calculation

- crates/utils/src/math.cairo
- crates/utils/src/tests/test_math.cairo
Adds all maths utils required by #699.
Resolves: #702 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/703)
> feat: add math helpers required for #699 { modexp precompile }

- crates/evm/src/state.cairo
Resolves: #707 
`is_account_alive` checks in the global state if the contract account exists.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/708)
> bug: fix `is_account_alive` function

- crates/alexandria_data_structures/src/vec.cairo
- crates/evm/src/errors.cairo
- crates/evm/src/precompiles/blake2f.cairo
- crates/evm/src/precompiles/ec_recover.cairo
- crates/evm/src/tests/test_gas.cairo
- crates/evm/src/tests/test_precompiles/test_ec_recover.cairo
- crates/utils/src/address.cairo
- crates/utils/src/helpers.cairo
- crates/utils/src/rlp.cairo
- crates/utils/src/tests/test_eth_transaction.cairo
- crates/utils/src/tests/test_helpers.cairo
Adds Felt252Vec utils used in #699.
Resolves: #713 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/714)
> feat: add vec utils

- crates/evm/src/precompiles/blake2f.cairo
- crates/evm/src/precompiles/ec_recover.cairo
- crates/evm/src/tests/test_precompiles/test_blake2f.cairo
- crates/evm/src/tests/test_precompiles/test_ec_recover.cairo
- crates/evm/src/tests/test_precompiles/test_sha256.cairo
- crates/utils/src/checked_math.cairo
- crates/utils/src/crypto.cairo
- crates/utils/src/crypto/modexp.cairo
- crates/utils/src/crypto/modexp/arith.cairo
- crates/utils/src/crypto/modexp/lib.cairo
- crates/utils/src/crypto/modexp/mpnat.cairo
- crates/utils/src/helpers.cairo
- crates/utils/src/math.cairo
- crates/utils/src/rlp.cairo
- crates/utils/src/tests.cairo
- crates/utils/src/tests/test_eth_transaction.cairo
- crates/utils/src/tests/test_helpers.cairo
- crates/utils/src/tests/test_modexp.cairo
- crates/utils/src/tests/test_modexp/test_arith.cairo
- crates/utils/src/tests/test_modexp/test_mpnat.cairo
- tsconfig.json
Resolves: #711
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/718)
> feat: add ModExp core lib

- .github/workflows/release.yml
https://github.com/d-roak/kakarot-ssj/actions/runs/7800082155
https://github.com/d-roak/kakarot-ssj/releases/tag/v0.1.0
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/728)
> ci: add release workflow and artifacts upload

- crates/contracts/src/precompiles.cairo
Resolves: #
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/730)
> feat: add modexp to precompiles library

- crates/contracts/src/kakarot_core/interface.cairo
- crates/contracts/src/kakarot_core/kakarot.cairo
- crates/contracts/src/tests/test_kakarot_core.cairo
- crates/contracts/src/tests/test_utils.cairo
- crates/evm/src/tests/test_utils.cairo
Resolves: #729 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/732)
> dev: Remove deploy fee

- .all-contributorsrc
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/733)
> dev: add `bajpai244` as countributor

- .github/workflows/ef_tests.yml
Resolves: #
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/735)
> update ef-tests setup

- crates/contracts/src/precompiles.cairo
Resolves: #
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/739)
> feat: expose block hash as library call

- .github/workflows/release.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/741)
> fix: remove path structure on release zip

- crates/contracts/src/cairo1_helpers.cairo
- crates/contracts/src/lib.cairo
Related to https://github.com/kkrt-labs/kakarot-ssj/issues/738
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/740)
> [dev] Rename Precompiles module to Cairo1Helpers

- crates/contracts/src/cairo1_helpers.cairo
- crates/contracts/src/tests.cairo
- crates/contracts/src/tests/test_cairo1_helpers.cairo
Resolves: #
- Add a solidity-compatible keccak helper that uses the new keccak syscall, aimed for the Cairo0 contracts.
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/752)
> feat: keccak cairo1 helper

- crates/contracts/src/tests/test_utils.cairo
- crates/evm/src/instructions/environmental_information.cairo
- crates/evm/src/interpreter.cairo
- crates/evm/src/model/account.cairo
- crates/evm/src/state.cairo
- crates/evm/src/tests/test_instructions/test_environment_information.cairo
- crates/evm/src/tests/test_instructions/test_memory_operations.cairo
- crates/evm/src/tests/test_instructions/test_system_operations.cairo
- crates/evm/src/tests/test_model.cairo
- crates/evm/src/tests/test_model/test_contract_account.cairo
- crates/evm/src/tests/test_state.cairo
- crates/evm/src/tests/test_utils.cairo
- crates/utils/src/constants.cairo
Resolves: #764
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/765)
> feat: merge CA / EOA in account model

- crates/contracts/src/kakarot_core/interface.cairo
- crates/contracts/src/kakarot_core/kakarot.cairo
- crates/contracts/src/tests/test_eoa.cairo
- crates/contracts/src/tests/test_kakarot_core.cairo
- crates/contracts/src/tests/test_utils.cairo
- crates/evm/src/backend/starknet_backend.cairo
- crates/evm/src/model.cairo
- crates/evm/src/tests/test_utils.cairo
Resolves: #767 
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/775)
> feat: add extra constructor args

- crates/contracts/src/cairo1_helpers.cairo
- crates/contracts/src/lib.cairo
- crates/contracts/src/mocks/cairo1_helpers_fixture.cairo
Resolves: #
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/777)
> dev: create cairo1helpers fixture

- crates/contracts/src/cairo1_helpers.cairo
> feat: recover eth address cairo1 helper

- crates/contracts/src/account_contract.cairo
- crates/contracts/src/kakarot_core/interface.cairo
- crates/contracts/src/kakarot_core/kakarot.cairo
- crates/contracts/src/tests/test_eoa.cairo
EIP1559 checks in `__validate__` function
Resolves: #742
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/778)
> feat: EIP1559 checks

- crates/evm/src/backend/starknet_backend.cairo
- crates/evm/src/call_helpers.cairo
- crates/evm/src/instructions/environmental_information.cairo
- crates/evm/src/instructions/memory_operations.cairo
- crates/evm/src/interpreter.cairo
- crates/evm/src/model.cairo
- crates/evm/src/model/account.cairo
- crates/evm/src/state.cairo
- crates/evm/src/tests/test_instructions/test_memory_operations.cairo
- crates/evm/src/tests/test_state.cairo
- crates/evm/src/tests/test_utils.cairo
Resolves: #
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/781)
> dev: cleaning

- crates/evm/src/interpreter.cairo
- crates/evm/src/model/account.cairo
- crates/evm/src/model/vm.cairo
- crates/evm/src/tests/test_instructions/test_memory_operations.cairo
- crates/evm/src/tests/test_model/test_vm.cairo
- crates/evm/src/tests/test_utils.cairo
Resolves: #761
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/782)
> dev: make valid jumpdests a dict

- crates/contracts/src/cairo1_helpers.cairo
Needs to validate x,y !=(0,0)
Resolves: #
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/784)
> fix: recover eth address cairo1 helpers

- crates/contracts/src/account_contract.cairo
- crates/evm/src/instructions/block_information.cairo
- crates/evm/src/instructions/memory_operations.cairo
Resolves: #
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/785)
> feat: read prevrandao from env

- blockchain-tests-skip.yml
Resolves: #
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/786)
> fix: skipfile

- crates/contracts/src/cairo1_helpers.cairo
Resolves: #
- Adds secp256r1 signature verification in the list of cairo1 helpers 
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/793)
> feat: secp256r1 cairo1 verify

- crates/contracts/src/account_contract.cairo
Resolves: #
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/798)
> feat: signature length expected 6

- crates/contracts/src/account_contract.cairo
Reverts kkrt-labs/kakarot-ssj#798
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/799)
> Revert "feat: signature length expected 6"

- crates/utils/src/crypto/blake2_compress.cairo
Just cleaned code, no change in behavior. No relevant issue.
- No change in behavior.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/797)
> clean: remove no op in blake2_compress

- crates/alexandria_math/src/sha256.cairo
- crates/alexandria_storage/src/list.cairo
- crates/utils/Scarb.toml
- crates/utils/src/address.cairo
- crates/utils/src/checked_math.cairo
- crates/utils/src/constants.cairo
- crates/utils/src/crypto/blake2_compress.cairo
- crates/utils/src/crypto/modexp/arith.cairo
- crates/utils/src/crypto/modexp/mpnat.cairo
- crates/utils/src/errors.cairo
- crates/utils/src/eth_transaction.cairo
- crates/utils/src/fmt.cairo
- crates/utils/src/helpers.cairo
- crates/utils/src/i256.cairo
- crates/utils/src/lib.cairo
- crates/utils/src/math.cairo
- crates/utils/src/rlp.cairo
- crates/utils/src/serialization.cairo
- crates/utils/src/set.cairo
- crates/utils/src/storage.cairo
- crates/utils/src/traits.cairo
Resolves: #
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/803)
> chore: bump utils to 2023_10

- crates/contracts/src/kakarot_core/kakarot.cairo
- crates/evm/src/backend/starknet_backend.cairo
- crates/evm/src/gas.cairo
- crates/evm/src/instructions/duplication_operations.cairo
- crates/evm/src/instructions/environmental_information.cairo
- crates/evm/src/instructions/push_operations.cairo
- crates/evm/src/instructions/sha3.cairo
- crates/evm/src/memory.cairo
- crates/evm/src/model/account.cairo
- crates/evm/src/precompiles/blake2f.cairo
- crates/evm/src/precompiles/sha256.cairo
- crates/evm/src/stack.cairo
- crates/evm/src/state.cairo
- crates/evm/src/test_utils.cairo
- crates/utils/src/crypto/blake2_compress.cairo
- crates/utils/src/crypto/modexp/arith.cairo
- crates/utils/src/eth_transaction.cairo
- crates/utils/src/helpers.cairo
- crates/utils/src/math.cairo
- crates/utils/src/rlp.cairo
- crates/utils/src/serialization.cairo
- crates/utils/src/set.cairo
- crates/utils/src/storage.cairo
- crates/utils/src/traits.cairo
Closes #809
Resolves: #
- Changes loop syntaxes to `for x in arr` and `while | while let ` where applicable.
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/816)
> dev: change loop syntaxes

- crates/utils/src/helpers.cairo
- crates/utils/src/math.cairo
Closes #807
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/821)
> dev: fix import paths

- crates/utils/src/lib.cairo
- crates/utils/src/utils.cairo
Resolves: #826
- Unpacks packed-felts arrays into big-endian bytes
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/831)
> feat: unpack big-endian felt-packed bytes

- .github/workflows/ci.yml
- .github/workflows/test.yml
Resolves: #
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/844)
> fix: ci deadlock

- Scarb.lock
- crates/evm/Scarb.toml
- crates/evm/src/precompiles.cairo
- crates/evm/src/precompiles/ec_add.cairo
- crates/evm/src/precompiles/ec_mul.cairo
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/855)
> feat: ec_add, ec_mul

- crates/evm/src/instructions/memory_operations.cairo
- crates/evm/src/memory.cairo
Resolves: #834
Implement `mcopy`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/866)
> feat: mcopy

- crates/evm/src/backend/starknet_backend.cairo
- crates/evm/src/create_helpers.cairo
- crates/evm/src/instructions/system_operations.cairo
- crates/evm/src/model.cairo
Resolves: #858 
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/861)
> feat: cancun selfdestruct

- crates/evm/src/instructions/block_information.cairo
Implementing ``` BLOBBASEFEE ``` evm code.
Currently there is no implementation of the ``` BLOBBASEFEE ``` evm code in the project.
Resolves: #852
- Added the necessary cairo code to implement BLOBBASEFEE.
- Added a test to ensure the code works fine.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/872)
> feat: implemented BLOBBASEFEE

- crates/contracts/src/cairo1_helpers.cairo
Resolves: #
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/916)
> feat: expose ecadd ecmul in cairo1helpers

- crates/evm/src/interpreter.cairo
Resolves: #
- Enables MCOPY opcode to be executed by the interpreter.
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/917)
> feat: enable mcopy

- .tool-versions
- Scarb.toml
- crates/alexandria_data_structures/Scarb.toml
- crates/contracts/Scarb.toml
- crates/contracts/tests/test_contract_account.cairo
- crates/evm/Scarb.toml
- crates/evm/src/precompiles/ec_add.cairo
- crates/evm/src/precompiles/ec_mul.cairo
- crates/openzeppelin/Scarb.toml
- crates/snforge_utils/Scarb.toml
- crates/utils/Scarb.toml
Resolves: #
- Updates Cairo to 2.8.2
- Removes reliance on internal corelib stuff in ec_add and ec_mul
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/918)
> chore: bump cairo to 2.8.2

- crates/utils/src/serialization.cairo
- scripts/compute_rlp_encoding.ts
- scripts/data/input_eip1559_y_parity_false.json
Resolves: #
- Fixes an issue when deserializing a Array<felt252> signature, where y_parity was wrongly computed.
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/934)
> fix: signature y parity deserialization

- crates/evm/src/backend/validation.cairo
Resolves: #
- Intrinsic gas should be lower **or equal** to the gas limit.
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/935)
> fix: intrinsic gas validatoin

- crates/evm/src/interpreter.cairo
Resolves: #
- Enables the SHA3 (keccak256) opcode for execution.
- Convert decimal opcode notation to hex
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/938)
> fix: sha3 opcode

- crates/contracts/Scarb.toml
- crates/evm/src/instructions/block_information.cairo
- crates/evm/src/test_utils.cairo
Resolves: #
- Fixes an issue where basefee was not pushing the environment basefee onto the stack.
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/956)
> fix: basefee opcode pushes base_fee value

- crates/utils/src/traits/eth_address.cairo
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/976)
> test: eth address trait

- Scarb.lock
- crates/alexandria_data_structures/Scarb.toml
- crates/contracts/Scarb.toml
- crates/evm/Scarb.toml
- crates/openzeppelin/Scarb.toml
- crates/snforge_utils/Scarb.toml
- crates/utils/Scarb.toml
Bumps snforge_std
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/982)
> dev: bump snforge_std

- crates/evm/src/instructions/stop_and_arithmetic_operations.cairo
fixes internal overflows in mulmod 
closes https://github.com/kkrt-labs/kakarot-ssj/issues/967
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/998)
> fix: mulmod

- scripts/setup_cairo_native.sh
downgrade cairo native due to a stack overflow issue when compiling to native.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/1008)
> ci: downgrade cairo native

- scripts/setup_cairo_native.sh
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/1013)
> dev: freeze working native in setup script
