src/errors.cairo, src/lib.cairo, src/stack.cairo, src/tests/test_stack.cairo
Issue Number: #45 
- Stack uses `Nullable<u256>` instead of using helper functions storing `(low,high)` limbs
-
-
Stack tests available_gas values have been reduced to a value close to the minimum required - it will allow us to detect eventual efficiency decreases
=> refactor: use Nullable<u256> in Stack

.github/workflows/test.yml, .tool-versions, README.md, Scarb.toml, src/memory.cairo, src/stack.cairo
Introduces a `.tool-versions` so that users having an installation of scarb through `asdf` don't have to manually manage which version of Scarb to use when working on Kakarot.
Issue Number: Closes #46 
- Intended Scarb version will be detected by asdf and used when running Scarb commands.
- Updated Cairo version to last release candidate
-
=> dev: update scarb & use asdf version management

src/memory.cairo, src/utils/helpers.cairo
Optimised `store_n` memory function by getting rid of useless array cloning and using newly introduced Span `slice` methods.
-
-
-
Gas usage results:
Before change
```shell
❯ scarb test -f test_store_should_add_n_elements_to_the_memory
testing kakarot ...
running 1 tests
[DEBUG]	                               	(raw: 0x1eb2e8
test kakarot::tests::test_memory::test_store_should_add_n_elements_to_the_memory ... ok
test result: ok. 1 passed; 0 failed; 0 ignored; 37 filtered out;
```
```shell
After change
❯ scarb test -f test_store_should_add_n_elements_to_the_memory
testing kakarot ...
running 1 tests
[DEBUG]	-V                            	(raw: 0x182d56
test kakarot::tests::test_memory::test_store_should_add_n_elements_to_t …
```
=> dev: memory optimisation

src/tests/test_utils.cairo, src/tests/test_utils/test_u256_signed_math.cairo, src/utils.cairo, src/utils/helpers.cairo, src/utils/u256_signed_math.cairo
Implements a math library to perform division on u256s signed values encoded as two's complement.
Issue Number: #62 
- Source & tests for two's complement division.
-
-
=> feat:two's complement division

src/instructions/stop_and_arithmetic_operations.cairo, src/memory.cairo, src/tests/test_instructions/test_stop_and_arithmetic_operations.cairo, src/tests/test_memory.cairo, src/tests/test_utils.cairo, src/tests/test_utils/test_math.cairo, src/utils.cairo, src/utils/math.cairo
Issue Number: Closes #72, Closes #73 
- mod-related opcodes are now wrapping back to 0 instead of overflowing
- implements the 0x0A-EXP opcode (modulo 256 exponentiation)
- Re-ordered test functions so that they match the opcode numbers and implementation order
=> feat: Opcode 0x0A - EXP

CHANGELOG.md, src/instructions/stop_and_arithmetic_operations.cairo, src/tests/test_instructions/test_stop_and_arithmetic_operations.cairo, src/utils/math.cairo
Issue Number: Closes #4 Closes #63
- Implements the MULMOD opcode
-
-
I tried two different implementations for this MULMOD opcode, leveraging the fact that `// (x * y) mod N <=> (x mod N) * (y mod N) mod N` 
The first try was using u256_wide_mul to avoid overflowing on the a*b multiplication, and then dividing it by N and returning the remainder.
```rust
 fn exec_mulmod(ref self: ExecutionContext) {
let popped = self.stack.pop_n(3);
let n: u256 = *popped[2];
let mut result = 0;
if n != 0 {
result = u256_mul_mod(*popped[0], *popped[1], n.try_into().unwrap())
}
self.stack.push(result);
}  fn u256_mul_mod(a: u256, b: u256, n: NonZero<u256>) -> u256 {
let wide_product = u256_wide_mul(a, b);
let (_, r) = …
```
=> feat: 0x09-MULMOD

CHANGELOG.md, src/instructions/stop_and_arithmetic_operations.cairo, src/tests/test_instructions/test_stop_and_arithmetic_operations.cairo, src/tests/test_utils/test_math.cairo, src/utils/math.cairo
Issue Number: Closes #83 
- Fixes ADDMOD behavior
-
-
ADDMOD
I tried two different implementations for this ADDMOD opcode, leveraging the fact that `(x + y) mod N <=> (x mod N) + (y mod N) mod N` 
The first try was using u256_wide_add, a function that I created that adds two u256s and returns a u512 to avoid overflowing on the a+b addition, and then dividing it by N and returning the remainder.
```rust
     fn exec_addmod(ref self: ExecutionContext) {
let popped = self.stack.pop_n(3);
let n: u256 = *popped[2];
let mut result = 0;
if n != 0 {
let add_res = u256_wide_add(*popped[0], *popped[1]);
let (_, r) = u512_safe_div_rem_by_u256(add_res, n.try_into().unwrap());
result = r;
}
self.stack.push(result);
}
  fn u256_wide_add(a: u256, b: …
```
=> fix: addmod

CHANGELOG.md, src/instructions/stop_and_arithmetic_operations.cairo, src/tests/test_utils/test_u256_signed_math.cairo, src/utils/u256_signed_math.cairo
Refactors `u256_signed_div` to enforce `div !=0` through the type system.
This is open to discussion if you believe that the benefits are not high enough to implement it.
Issue Number: Closes #89 
- Zero case is explicitly handled in SDIV opcode
-
-
=> refactor: u256_signed_div

CHANGELOG.md, src/instructions/stop_and_arithmetic_operations.cairo, src/tests/test_instructions/test_stop_and_arithmetic_operations.cairo, src/tests/test_utils/test_u256_signed_math.cairo, src/utils/u256_signed_math.cairo
Issue Number: Closes #93 Closes #100
- 
-
-
=> feat: 0x0B -SIGNEXTEND

.github/workflows/gas_reports.yml, CHANGELOG.md, scripts/compare_snapshot.py
Issue Number: Closes #163 
-
-
-
=> feat: add gas-comparison PR bot

CHANGELOG.md, scripts/install_hook.sh
- [✔️] Feature
Project does not have inbuilt format before pushing new changes
Issue Number: Closes #165
On commit, pre-commit hook will format the project with "scarb fmt" 
- Added changes to install-hook.sh file for adding pre-commit
- [] Yes
- [✔️] No
- [✔️] Yes
=> dev: add pre-commit hook to format project

crates/evm/src/instructions/comparison_operations.cairo, crates/evm/src/instructions/duplication_operations.cairo, crates/evm/src/instructions/stop_and_arithmetic_operations.cairo, crates/evm/src/tests/test_instructions/test_comparison_operations.cairo, crates/evm/src/tests/test_instructions/test_duplication_operations.cairo, crates/evm/src/tests/test_instructions/test_stop_and_arithmetic_operations.cairo, crates/evm/src/tests/test_stack.cairo
Related: #141 
- Linked PR missed to add this operator during refactoring, so fixed it.
- Without this it won't propagate stackoverflow error and ignore it silently.
- Inside tests call `unwrap` on methods that can fail
- due to this `unwrap`s needed to increase gas for few tests
=> bug: add missing `?` operators in methods and `unwrap`s in tests

.github/workflows/gas_reports.yml
Fixes action trigger condition
Resolves: #
-
-
-
=> fix: gas reports

crates/evm/src/instructions.cairo, crates/evm/src/instructions/push_operations.cairo, crates/evm/src/interpreter.cairo, crates/evm/src/tests/test_instructions.cairo, crates/evm/src/tests/test_instructions/test_push_operations.cairo, crates/evm/src/tests/test_utils.cairo
=> feat(evm): add push{i} opcodes

crates/evm/src/instructions/environmental_information.cairo, crates/evm/src/tests/test_instructions/test_environment_information.cairo
=> fix: integer underflow

crates/evm/src/context.cairo, crates/evm/src/instructions/environmental_information.cairo, crates/evm/src/tests/test_execution_context.cairo, crates/evm/src/tests/test_instructions/test_environment_information.cairo, crates/evm/src/tests/test_utils.cairo, docs/general/model/execution_context.md
Fixing call_data to calldata
Resolves: #269 
-
-
-
=> Fix call_data to calldata

crates/evm/src/context.cairo, crates/evm/src/instructions.cairo, crates/evm/src/instructions/memory_operations.cairo, crates/evm/src/interpreter.cairo, crates/evm/src/tests/test_instructions.cairo, crates/evm/src/tests/test_instructions/test_comparison_operations.cairo, crates/evm/src/tests/test_instructions/test_memory_operations.cairo
Resolves: #254 #255 
- implements `PC` opcode
- kakarot on cairo0 just increments the PC manually, which I don't think will be very useful
- i didn't find tests related PC specifically in geth.
- evm.codes also dont specify any examples.
=> feat: implement PC opcode

crates/evm/src/instructions/comparison_operations.cairo, crates/evm/src/tests/test_instructions/test_comparison_operations.cairo
Resolves: #5 
- Implement LT opcode during workshop.
- `exec_lt` returns 1 if a < b, returns 1. Otherwise, 0.
-
=> implement LT opcode

crates/evm/src/memory.cairo, crates/evm/src/tests/test_memory.cairo
Resolves: #270 
- Array is now moved 16 elements further instead of staying the same
-
-
=> fix: store_aligned_words slice

crates/evm/src/memory.cairo, crates/evm/src/stack.cairo, scripts/compare_snapshot.py
see title and PR bot comment
Resolves: #294 
- Inlined stack and memory functions for gas optimisations
-
-
=> feat: inline stack/memory methods

crates/evm/src/instructions/comparison_operations.cairo, crates/evm/src/tests/test_instructions/test_comparison_operations.cairo
Added OR opcode
Enhancement OpCode
- [x ] Feature
=> implement 0x17 - OR opcode #12

crates/evm/src/memory.cairo, crates/evm/src/tests/test_memory.cairo
Great catch @khaeljy ! There was a missing explicit return statement!
Resolves: #327 
- Fixes load_internal behavior
-
-
=> fix: load_n_internal

.github/workflows/gas_reports.yml
The gas report CI is not allowed to post on PR page. After some research, it seems like the only way to have such a feature would be:
- long and honest: create an app (like codecov)
- short and hacky: create a personal token and use it, the user owning the token would be the posting username
See also: https://github.com/actions/first-interaction/issues/10
Since the detailed output is also visible in the CI logs, I've just removed the comment step to have the job pass if there is no change and fail otherwise
=> Fix compare_snapshot CI

crates/evm/src/errors.cairo, crates/evm/src/instructions/memory_operations.cairo, crates/evm/src/tests/test_instructions/test_memory_operations.cairo
Resolves: #251
- evm.codes doesn't contain an example for this
- i couldn't find test for this in geth or kakarot cairo0 (lmk if i missed something)
- i think thats because there are only 2 cases, one in which location to which we need to jump is `JUMPDEST` (in that case its valid) else its invalid
- actually there is one more case in which: `0x5B` is part of data segment and is not an opcode (in an PUSHN) context.
- kakarot 0 also doesn't handle this case, i will see geth's code and figure out how to implement this.
=> feat: add tests for JUMP instruction

crates/evm/src/instructions.cairo, crates/evm/src/instructions/system_operations.cairo, crates/evm/src/interpreter.cairo, crates/evm/src/tests/test_instructions.cairo, crates/evm/src/tests/test_instructions/test_system_operations.cairo
=> feat(evm): add exec_return opcode

crates/evm/src/instructions/comparison_operations.cairo, crates/utils/src/math.cairo, crates/utils/src/tests/test_math.cairo
Split Bitshift into two traits, Modified the existing implementations of bitshift, Removed the shl and shr implementations for felt252, Added support for wrapping_shr for the felt252 type by converting the value to u256, doing the operations, and then back to felt252 instead of panicking
wrapping_shl and wrapping_shl implemented as part of the Bitshift trait. 
Resolves: #338 
split Bitshift into Bitshift and WrappingBitshift traits by adding a new WrappingBitshift trait and moving the logic for wrapping bitshifts into it. Added support for felt252 wrapping shr, and tests for the felt252 type. Removed implementations for felt252 shl and shr
=> Feat: Divide Bitshift into Bitshift and WrappingBitshift

crates/evm/src/instructions/memory_operations.cairo, crates/evm/src/tests/test_instructions/test_memory_operations.cairo
Resolves: #253 
- didn't find test for this in kakarot0, evm.codes, geth
- execution spec has something to test jumpi [(but it tests something very different)](https://github.com/ethereum/execution-specs/blob/master/tests/constantinople/vm/test_control_flow_operations.py) 
- out of bounds and those tests are not required because we would be using implementation of `JUMP` opcode to implement `JUMPI` which tests those cases.
=> feat: implement JUMPI tests

crates/utils/src/helpers.cairo, crates/utils/src/tests/test_helpers.cairo
For the sake of consitency, we are switching the syntax of endian wording.
=> Fix: changed endian syntax to le/be

crates/evm/src/instructions/memory_operations.cairo, crates/evm/src/memory.cairo, crates/evm/src/tests/test_instructions/test_memory_operations.cairo, crates/evm/src/tests/test_memory.cairo, crates/utils/src/helpers.cairo, crates/utils/src/math.cairo, scripts/compare_snapshot.py
Resolves: #325 
- Adds a `store_byte` method to memory for MSTORE8 opcode
- Fixes total gas accounting in python script.
-
=> feat: store_byte memory method

.github/workflows/gas_reports.yml
Summary is not displayed in action when failure
Displayed in both success and failure.
=> Fix no GITHUB_STEP_SUMMARY

crates/evm/src/stack.cairo, crates/evm/src/tests/test_instructions/test_comparison_operations.cairo, crates/evm/src/tests/test_instructions/test_environment_information.cairo, crates/evm/src/tests/test_instructions/test_stop_and_arithmetic_operations.cairo, crates/evm/src/tests/test_stack.cairo, scripts/compare_snapshot.py
=> feat: update stack

crates/evm/src/memory.cairo, crates/utils/src/i256.cairo
=> Dev: replace all `*_div_rem` by `DivRem::div_rem`

crates/evm/src/instructions/environmental_information.cairo, crates/evm/src/tests/test_instructions/test_comparison_operations.cairo, crates/evm/src/tests/test_instructions/test_environment_information.cairo, crates/evm/src/tests/test_instructions/test_stop_and_arithmetic_operations.cairo, crates/evm/src/tests/test_stack.cairo
=> feat: implement exec_caller

crates/evm/src/context.cairo, crates/evm/src/interpreter.cairo, crates/evm/src/machine.cairo, crates/evm/src/tests/test_execution_context.cairo, crates/evm/src/tests/test_machine.cairo, crates/evm/src/tests/test_utils.cairo, docs/general/execution_context.md, docs/general/machine.md
Resolves: #387 
- Each context has only a parent context field that tracks its parent inside a Nullable smart pointer
- Instead of having a child context field, it simply has a child_context_return_data
=> refactor: refactor child context to be child context return data

crates/evm/src/kakarot_core.cairo, crates/evm/src/lib.cairo
=> feat: create kakarot core smart contract

crates/evm/src/context.cairo, crates/evm/src/instructions/environmental_information.cairo, crates/evm/src/instructions/stop_and_arithmetic_operations.cairo, crates/evm/src/instructions/system_operations.cairo, crates/evm/src/interpreter.cairo, crates/evm/src/machine.cairo, crates/evm/src/tests/test_execution_context.cairo, crates/evm/src/tests/test_instructions/test_environment_information.cairo, crates/evm/src/tests/test_instructions/test_system_operations.cairo, crates/evm/src/tests/test_machine.cairo, crates/evm/src/tests/test_utils.cairo, docs/general/execution_context.md, docs/general/machine.md
Resolves: #383
- Correct behavior of returndatasize/returndatacopy
- Got rid of the `child_return_data` field
- `return_data` now refers to the return_data of the last executed subcontext
- renamed machine `revert` and `stop` to `set_reverted` and `set_stopped` to avoid confusion with `revert` and `stop` opcodes
- Unexpected revert (not the REVERT Opcode) reason is not appended to the parent's return data field.
=> fix: returndata

crates/contracts/Scarb.toml, crates/contracts/src/contract_account.cairo, crates/contracts/src/lib.cairo, crates/contracts/src/tests.cairo, crates/contracts/src/tests/test_contract_account.cairo, crates/contracts/src/tests/utils.cairo, crates/evm/src/context.cairo, crates/evm/src/instructions/sha3.cairo, crates/evm/src/memory.cairo, crates/evm/src/storage_journal.cairo, crates/evm/src/tests/test_instructions/test_environment_information.cairo, crates/evm/src/tests/test_memory.cairo, crates/utils/src/helpers.cairo, crates/utils/src/lib.cairo, crates/utils/src/storage.cairo, crates/utils/src/tests/test_helpers.cairo, crates/utils/src/tests/test_storage.cairo, crates/utils/src/traits.cairo
Currently implemented:
- feat: storage of bytecode (full bytes31 words)
Resolves: #423 
- #423 
-
-
=> feat: contract account bytecode storage

crates/utils/src/helpers.cairo
Resolves: #426
optimize deserialization of Span to ByteArray
=> dev: refactor from_byte

.trunk/trunk.yaml, crates/contracts/src/kakarot_core/kakarot.cairo, crates/evm/src/context.cairo, crates/evm/src/execution.cairo, crates/evm/src/machine.cairo, crates/evm/src/model.cairo, crates/evm/src/tests/test_execution_context.cairo, crates/evm/src/tests/test_machine.cairo, crates/evm/src/tests/test_utils.cairo
Resolves: #424
- Remove `starknet_address` field from the context
- Implements the `execute` function
- #424 
-
=> feat: execute

crates/contracts/src/contract_account.cairo, crates/contracts/src/kakarot_core.cairo, crates/contracts/src/kakarot_core/interface.cairo, crates/contracts/src/kakarot_core/kakarot.cairo, crates/contracts/src/tests/test_contract_account.cairo, crates/contracts/src/tests/test_kakarot_core.cairo, crates/evm/src/balance.cairo, crates/evm/src/errors.cairo, crates/evm/src/instructions/block_information.cairo, crates/evm/src/instructions/environmental_information.cairo, crates/evm/src/storage_journal.cairo, crates/evm/src/tests/test_balance.cairo, crates/utils/src/helpers.cairo, crates/utils/src/rlp.cairo, crates/utils/src/tests/test_helpers.cairo, crates/utils/src/traits.cairo
Defines a `ContractAccount` struct and its associated methods to interact with the storage of a Contract Account, embedded into the contract storage.
Defines a ByteArraySerde implementation that allows us to serialize/deserialize the ByteArray type. The first stored element in the serialized ByteArray is the `pending_word_len` - the last element is the `pending_word` - the elements are the full world.
Removes the explicit storage fields inside the KakarotCore Storage struct. Contract-Account related storage is now entirely performed in the ContractAccount module.
KakarotCore functions requiring interactions with the storage of a contract account need to first wrap an `evm_address` inside a `ContractAccount` struct, and then call the corresponding methods.
This allows for atomic querying …
=> feat: ContractAccount storage methods

crates/utils/src/helpers.cairo, crates/utils/src/rlp.cairo, crates/utils/src/tests/test_helpers.cairo, crates/utils/src/tests/test_rlp.cairo
- Refactored a bit how RLP is called introducing the RLPTrait
- Tiny improvements in RLP Type decoding by using __range checks only__ and not __range checks + equality checks__
- Implemented RLP string encoding.
- Added utils functions to know how many bytes a u32 uses and convert it to bytes
- Thoroughly tested the added utils and rlp_encoding
Resolves: #440
-
-
-
=> feat: rlp string encoding

crates/contracts/src/kakarot_core/kakarot.cairo, crates/evm/src/call_helpers.cairo, crates/evm/src/instructions/block_information.cairo, crates/evm/src/instructions/environmental_information.cairo, crates/evm/src/instructions/system_operations.cairo, crates/evm/src/model.cairo, crates/evm/src/model/contract_account.cairo, crates/evm/src/model/eoa.cairo, crates/evm/src/tests/test_model.cairo
Resolves: #
- fetch an account from SN storage and return a memory representation of it
- CA accounts load the nonce and byecode from storage
- EOA accounts simply return a struct with nonce=1
- If an account can't be fetched at address `address`, it means that it's an undeployed CA - it's instantiated empty in memory with a 0 nonce
- This means we have to refactor the way of knowing whether an account is a CA or an EOA or undeployed, #477 
-
-
=> feat: fetch account from SN

crates/utils/src/rlp.cairo, crates/utils/src/tests/test_rlp.cairo
When we encounter byte `[0x80]` we return `[]` i.e an empty slice, but we should return the default value `[0]` as per the spec.
Resolves: #499 
We return the default value `[0]` when we encounter the byte `[0x80]`.
=> fix: fix parsing of default value for int `0` from byte `[0x80]`

crates/contracts/src/kakarot_core/kakarot.cairo, crates/contracts/src/tests/test_kakarot_core.cairo, crates/contracts/src/tests/test_upgradeable.cairo, crates/contracts/src/uninitialized_account/uninitialized_account.cairo, crates/eoa/src/externally_owned_account.cairo
Resolves: #488 
- Updated `#[external(v0)]` to `#[abi(embed_v0)]` for contracts that implement interfaces
- `[external(v0)]` is not updated (don't think we should) in the `openzeppelin` crate,
- I didn't use the new notation `#[abi(per_item)]`, I don't feel like it's much applicable in the codebase since we have concrete interfaces for every contracts. I can use it if we maybe wrap the constructors into `impl` blocks, for example:
```rust
#[abi(per_item)]
#[generate_trait]
impl KakarotCoreConstructorImpl of KakarotCoreConstructor {
#[constructor]
fn constructor(
// ...
}
}
}
```
=> dev: Added new #[abi(embed_v0)] notation

crates/contracts/src/kakarot_core/interface.cairo, crates/contracts/src/kakarot_core/kakarot.cairo, crates/contracts/src/tests/test_kakarot_core.cairo, crates/evm/src/execution.cairo, crates/evm/src/instructions/environmental_information.cairo, crates/evm/src/model.cairo, crates/evm/src/model/account.cairo, crates/evm/src/model/contract_account.cairo, crates/evm/src/model/eoa.cairo, crates/evm/src/state.cairo, crates/evm/src/tests.cairo, crates/evm/src/tests/test_execution.cairo, crates/evm/src/tests/test_model.cairo, crates/evm/src/tests/test_model/test_contract_account.cairo, crates/utils/src/tests/test_eth_transaction.cairo
Refactors the account model and the way we interact with accounts to
- Make it safer by avoiding direct accesses to SN state
- Make it more consistent with the account model updates
- Prevents deployment of all undeployed accounts during commitment phase - First step for #519 is to check if the account must be deployed
- `StoredAccountType` is an internal type to the KakarotCore contract and is only used to check whether there is an account at a certain address, and what its actual type is. 
- `AccountType` methods disappeared in favour of `Account` methods. Eventually `AccountType` will disappear from the `Account` model - as we want to keep it as it's done in the EVM.
- Loads the Starknet Nonce of the origin into its evm account …
=> refactor: account model

crates/utils/src/eth_transaction.cairo, crates/utils/src/helpers.cairo, crates/utils/src/tests/test_data.cairo, crates/utils/src/tests/test_eth_transaction.cairo, crates/utils/src/tests/test_helpers.cairo
PR adds support for decoding EIP-2718 txns + improves testing for legacy decoding of transaction.
Decoding for EIP-2718 transactions is not supported.
Resolves: #406 
Decoding for EIP-2718 transactions is not supported.
=> feat: add eip-2718 tx decode

crates/utils/src/errors.cairo, crates/utils/src/eth_transaction.cairo, crates/utils/src/tests/test_eth_transaction.cairo
Implement `decode` and is `legacy tx` for [EthTransaction](implement `decode` and is `legacy tx`) utlils.
These methods are not implemented.
Resolves: #530 
-` decode` and is `legacy tx` are implemented
=> Feat: implement `decode` and is `legacy tx`

.trunk/trunk.yaml, crates/evm/src/create_helpers.cairo, crates/evm/src/instructions/environmental_information.cairo, crates/evm/src/model.cairo, crates/utils/src/eth_transaction.cairo, crates/utils/src/helpers.cairo, crates/utils/src/tests/test_helpers.cairo
Resolves: #516
- Span<u8> are not converted to ByteArray before packing them in u64 words
-
-
=> dev: optimize to_u64_words to use span<u8> as input

crates/contracts/src/contract_account.cairo, crates/contracts/src/eoa.cairo, crates/contracts/src/tests/test_eoa.cairo, crates/contracts/src/tests/test_kakarot_core.cairo, crates/evm/src/execution.cairo, crates/evm/src/tests/test_execution_context.cairo, crates/evm/src/tests/test_instructions/test_block_information.cairo, crates/evm/src/tests/test_instructions/test_memory_operations.cairo
Resolves: #
- Guard functions in Contract Account
- Moved `ignored` tests to `should_panic` instead - after thinking about it it makes more sense to expect a panic for a feature not working/not implemented than just ignoring the test, as we will directly notice that the test result changed if we changed a function
- Tests for KakarotCore contract-account related functions
- `reverted_with_err` function in `execute` to avoid code dup
=> feat: implement some remaining todos

crates/evm/src/call_helpers.cairo
The separation of target address and the code address are not supported, this PR adds support for this and fixed the bug to resolve `to` address correctly.
Resolves: #551 #552 
- target and code address has been seperated
- the correct `to` address is now resolved.
=> feat: seperate target address and the code address

crates/evm/src/tests/test_instructions/test_system_operations.cairo
The [current test](https://github.com/kkrt-labs/kakarot-ssj/blob/8597c6c8768c433778a819bf3ff20cf52b6b0e04/crates/evm/src/tests/test_instructions/test_system_operations.cairo#L335) doesn't test the behaviour delegate call properly.
Resolves: #550 
- The bytecode which is executed does SSTORE
- SSTORE of value 0x42 is done at key 0x42
- The existence of value is checked in the storage in the contract which made the delegate call
- This makes sure that opcode is properly being tested.
- [  ] Yes
=> feat: delegate call test

crates/contracts/src/kakarot_core/kakarot.cairo, crates/contracts/src/tests/test_eoa.cairo, crates/contracts/src/tests/test_kakarot_core.cairo, crates/evm/src/instructions/block_information.cairo, crates/evm/src/model/eoa.cairo, crates/evm/src/tests/test_instructions/test_block_information.cairo
The coinbase opcode doesn't give a Kakarot registered EVM address.
Resolves: #577 
- The coinbase opcode gives a Kakarot registered EVM address.
=> feat: fix coinbase

.github/workflows/gas_snapshot.yml
Adds a `workflow_dispatch` to enable triggering the workflow from GH UI
=> ci: add workflow dispatch event

crates/evm/src/instructions/memory_operations.cairo, crates/evm/src/interpreter.cairo, crates/evm/src/model/vm.cairo, crates/evm/src/tests/test_instructions/test_memory_operations.cairo, crates/evm/src/tests/test_model.cairo, crates/evm/src/tests/test_model/test_vm.cairo
This PR adds a new `valid_jump_destinations` to the execution context, which when initialised should contain indexes which are valid jump destinations.
Resolves: #544 
- Jumps to only valid jump destinations will be permitted, i.e if 0x5b is an argument to PUSH, then it cannot be confused for a valid jump.
=> feat: valid jumps

crates/evm/src/call_helpers.cairo, crates/evm/src/instructions/memory_operations.cairo, crates/evm/src/interpreter.cairo, crates/evm/src/model.cairo, crates/evm/src/model/vm.cairo, crates/evm/src/tests/test_instructions/test_memory_operations.cairo, crates/evm/src/tests/test_machine.cairo, crates/evm/src/tests/test_utils.cairo
Resolves: #630 #622
- Refactors the `gas_used` field to use `gas_left` instead - as all accountability and querying of gas inside the EVM is performed against the gas left
- Overrides #623 
-
=> refactor: gas_left VM field

crates/contracts/src/eoa.cairo, crates/contracts/src/tests/test_eoa.cairo, crates/utils/src/traits.cairo
We don't emit an event for a transaction's execution inside `__execute__`, which is done in case of [KKRT-0](https://github.com/kkrt-labs/kakarot/blob/92ab8dffd63ecfa967ac834c88c554026b7e05ad/src/kakarot/accounts/eoa/library.cairo#L28).
Resolves: #619 
- We emit event inside `__execute__`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/636)
=> feat: add event emission to `__execute__`

crates/contracts/src/eoa.cairo, crates/contracts/src/tests/test_eoa.cairo, crates/utils/src/constants.cairo, crates/utils/src/eth_transaction.cairo, crates/utils/src/helpers.cairo, crates/utils/src/tests/test_helpers.cairo, crates/utils/src/traits.cairo, scripts/compute_rlp_encoding.ts
The extraction of `y_parity` for legacy transactions is left to the RPC.
Resolves: #
- The extraction of `y_parity` for legacy transactions is done on kakarot EOA itself.
- The new eth signature format is: `[tx_type, r.low, r.high, s.low, s.high, v || y_parity]`
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/643)
=> feat: put extraction of y_parity in kakarot codebase

crates/evm/src/instructions/memory_operations.cairo, crates/evm/src/model/account.cairo, crates/evm/src/state.cairo, crates/evm/src/tests/test_instructions/test_memory_operations.cairo
Resolves: #656 
Accounts can be either
- unalive && undeployed (and thus, "Unkown")
- alive && undeployed (and thus, their type is set - alive means that it's in the state but not commited yet)
In this PR
- Added a check to ensure that when reading from state, the account is __deployed__
- Added a related test
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/658)
=> fix: read state on undeployed alive account

crates/contracts/src/kakarot_core/kakarot.cairo, crates/evm/src/interpreter.cairo, crates/evm/src/model.cairo, crates/evm/src/model/account.cairo, crates/evm/src/state.cairo, crates/evm/src/tests/test_state.cairo
- When submitting a TX, we charge the total gas fee to the sender before executing the transaction, ensuring that if the entire gas is consumed the user is charged accordingly
- The unused gas is refunded after the execution
- When clearing storage slots, gas can be refunded. The maximum amount refunded is `gas_used // 5`, and the actual gas refunded is min(gas_used //5, refunded_gas)
- Created a new issue for gas refunds
Resolves: #671
- Charges tx gas fee
- Refund unused gas after the execution of a transcation
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/682)
=> feat(gas): charge tx gas fee

crates/contracts/src/kakarot_core/kakarot.cairo, crates/contracts/src/tests/test_kakarot_core.cairo, crates/contracts/src/tests/test_utils.cairo
Feature added to kakarot contract constructor.
Resolves: #588
KakarotCore contract is able to receive multiple EthAddress as arguments, and deploy them during constructor execution. 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/685)
=> feat: pre_deployed_eoas in kakarot constructor

crates/contracts/src/kakarot_core/kakarot.cairo, crates/evm/src/instructions/memory_operations.cairo, crates/evm/src/interpreter.cairo, crates/evm/src/model.cairo, crates/evm/src/model/vm.cairo, crates/evm/src/tests/test_utils.cairo
Resolves: #683 
- Implements the gas refund mechanism
- Simplifies the gas fee payment mechanism by paying only AFTER the execution - rationale is that since env.gas_price == tx.gas_price and we don't have support for EIP-1559 transactions, we can simply charge (gas_used - gas_refund) gas to the user in a single step
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/686)
=> feat: gas refunds

crates/contracts/src/kakarot_core/kakarot.cairo
Resolves: #
- as EF-Tests is not ready for this, revert this to have better metrics on passing/failing tests due to other reasons than gas.
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/692)
=> revert charging eth for gas usage

crates/contracts/src/kakarot_core/interface.cairo, crates/contracts/src/kakarot_core/kakarot.cairo
Resolves: #696 
`gas_used` is added in the return data of `eth_call` function in KakarotCore contract.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/698)
=> feat: include `gas_used` in `eth_call` return data

crates/contracts/Scarb.toml, crates/contracts/src/lib.cairo, crates/contracts/src/precompiles.cairo
Precompiles are available within an EVM run only.
Resolves: https://github.com/kkrt-labs/kakarot/issues/909
Added a Precompiles contract with one `exec_precompile` entrypoint to run a precompile.
Note: I've just put the SHA256 has it's the only one missing currently for Kakarot0. I don't know if it's worth adding them all.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/710)
=> Add a Precompiles contract

crates/evm/src/precompiles/modexp.cairo, crates/utils/src/crypto/modexp/mpnat.cairo, crates/utils/src/helpers.cairo, crates/utils/src/tests/test_helpers.cairo
Resolves: #
- Fix `bits_used`
- add Modexp to Precompiles library
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/734)
=> fix: bits_used when value is 0

crates/contracts/src/kakarot_core/kakarot.cairo
Resolves: #771 
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/773)
=> refactor: rename storage vars

crates/evm/src/call_helpers.cairo, crates/evm/src/precompiles.cairo, crates/evm/src/precompiles/p256verify.cairo, crates/evm/src/tests/test_instructions/test_system_operations.cairo, crates/evm/src/tests/test_precompiles.cairo, crates/evm/src/tests/test_precompiles/test_p256verify.cairo
Add the precompiled contracts p256verify to the list of precompiled contracts at address 0x0b following this implementation : https://github.com/ethereum/go-ethereum/pull/27540 .
I have chosen the 0x0b instead of 0x100 because of the amount of lines that the second one would have added to the precompiles.cairo and I am currently unaware of a precompiled contract at address 0x0b.
Resolves: #755 
- p256verify is now added to the list of precompiled contract at address 0x0b
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/779)
=> Feat: add RIP-7212 to the list of precompiles Cairo1Helpers module

crates/contracts/src/cairo1_helpers.cairo
Resolves: #
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/783)
=> restore verify_eth_signature

crates/evm/src/interpreter.cairo, crates/evm/src/model/account.cairo, crates/evm/src/tests/test_instructions/test_memory_operations.cairo, crates/evm/src/tests/test_model.cairo, crates/evm/src/tests/test_state.cairo, crates/evm/src/tests/test_utils.cairo
Resolves: #788 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/789)
=> feat: mark accounts created in a tx as `created` 

crates/evm/src/precompiles/p256verify.cairo, crates/evm/src/tests/test_precompiles/test_p256verify.cairo
The current implementation doesn't meet with actual RIP-7212 behavior for the return values. It returns unwanted 0 value for some cases.
Resolves: #
The changes apply true behavior for the RIP-7212.
```
- **Output data:**
- If the signature verification process succeeds, it returns 1 in 32 bytes format.
- If the signature verification process fails, it does not return any output data.
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/790)
=> fix: rip-7212 implementation incorrect return value

crates/contracts/src/cairo1_helpers.cairo
Closes https://github.com/kkrt-labs/kakarot-ssj/issues/810.
Add `compute_sha256_u32_array` to `Cairo1Helpers`.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/813)
=> feat: expose sha256 in Cairo1Helpers class

crates/contracts/src/account_contract.cairo
currently I have :
error[E0002]: Method `write` could not be called on type `core::starknet::storage::storage_base::StorageBase::<core::integer::u256>`.
Candidate `StorageMapWriteAccess::write` inference failed with: Trait has no implementation in context: core::starknet::storage::map::StorageMapWriteAccess::<core::starknet::storage::storage_base::StorageBase::<core::integer::u256>>.
Candidate `StoragePointerWriteAccess::write` inference failed with: Trait has no implementation in context: core::starknet::storage::StoragePointerWriteAccess::<core::starknet::storage::storage_base::StorageBase::<core::integer::u256>>.
--> /Users/charlotte/kakarot-ssj/crates/contracts/src/account_contract.cairo:157:36
self.Account_code_hash.write(code_hash);
Resolves: #829
- - -
This change is [<img …
=> set_code_hash and get_code_hash

crates/contracts/src/account_contract.cairo, crates/contracts/src/test_utils.cairo, crates/contracts/src/uninitialized_account.cairo, crates/evm/src/backend/starknet_backend.cairo, crates/utils/src/helpers.cairo
Resolves: #860 
resolves  #863
- Address computation no longer takes kakarot_address as constructor argument, (now [1, evm_address]) and is DEPLOY_FROM_ZERO is now false, so that the deployer;s address (kakarot's) is used for computation of the address of the deployed contract
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/862)
=> feat: update starknet address computation method

crates/evm/src/interpreter.cairo
Resolves: #
- Fixes a bug where any changes made to the target_account during its initcode were being discarded, as we reused an old instance of `target_account` and overriding any previous state changes.
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/867)
=> fix: account state was discarded after processing created accounts initcode

crates/evm/src/precompiles/sha256.cairo
Resolves: #
- Fixes the sha256 output that wasnt converting each u32 chunk to word padded to 4-bytes
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/877)
=> fix: sha256 output was not forcing conversion of u32 words to 4-bytes

crates/evm/src/instructions/memory_operations.cairo, crates/evm/src/interpreter.cairo, crates/evm/src/state.cairo
Resolves: #846 
Resolves: #847 
TLOAD and TSTORE are implemented
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/873)
=> feat: TLOAD and TSTORE

crates/evm/src/instructions/memory_operations.cairo, crates/evm/src/test_utils.cairo
Resolves: #874
Test for EIP 1706 is added 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/875)
=> test: add missing test EIP-1706

Scarb.lock, crates/contracts/tests/test_kakarot_core.cairo, crates/evm/Scarb.toml, crates/evm/src/backend/starknet_backend.cairo, crates/evm/src/instructions/block_information.cairo, crates/evm/src/instructions/environmental_information.cairo, crates/evm/src/instructions/memory_operations.cairo, crates/evm/src/instructions/system_operations.cairo, crates/evm/src/model.cairo, crates/evm/src/model/account.cairo, crates/evm/src/precompiles/blake2f.cairo, crates/evm/src/precompiles/ec_recover.cairo, crates/evm/src/precompiles/identity.cairo, crates/evm/src/precompiles/modexp.cairo, crates/evm/src/precompiles/p256verify.cairo, crates/evm/src/precompiles/sha256.cairo, crates/evm/src/state.cairo, crates/evm/src/test_utils.cairo, crates/snforge_utils/Scarb.toml, crates/snforge_utils/src/contracts.cairo, crates/snforge_utils/src/lib.cairo, scripts/find_selectory.py
Resolves: #39
Resolves: #879 
- Migrated all tests in `evm` to NOT use deployed contracts - the testing strategy relies on setting up the local storage of the test_address with data if required, otherwise simply mocking calls
- Fixed tests that were ignored after the runner migration
- Cleared tests not relevant, made some more relevant
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/881)
=> tests: adapt testing strategy to leverage snforge feature

crates/evm/src/instructions/memory_operations.cairo
The stipend check performed in SSTORE (EIP-1706/EIP-2200) was performed AFTER charging the gas for the SSTORE operation. 
It should be performed right after popping the key and value, before charging any gas and modifying any state.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/893)
=> fix: sstore stipend check before charging gas

crates/evm/src/gas.cairo, crates/evm/src/instructions/block_information.cairo, crates/evm/src/interpreter.cairo
Resolves: #886
- Adds support for the blobhash opcode. It will always return Zero in the context of Kakarot.
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/889)
=> feat: blobhash opcode

crates/contracts/src/kakarot_core/kakarot.cairo, crates/evm/src/call_helpers.cairo, crates/evm/src/create_helpers.cairo, crates/evm/src/instructions/system_operations.cairo, crates/evm/src/interpreter.cairo, crates/evm/src/model.cairo, crates/evm/src/precompiles.cairo, crates/evm/src/test_utils.cairo
Resolves: #894
- Adds code_address in message struct
- Execution of precompiles is done by checking code_address, not target_address (as we can delegatecall to a precompile...)
- code_address is zero in case of deploy / create messages
- had to adapt tests for delegatecall / callcade that were calling 0x100 (RIP7212 reserved address) to another, non-conflicting address
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/901)
=> feat: add code address in message

crates/contracts/src/kakarot_core/kakarot.cairo, crates/evm/src/lib.cairo, crates/evm/src/model.cairo, crates/evm/src/precompiles.cairo, crates/utils/src/constants.cairo
Resolves: #
- Fixes warm up of precompiles by ensuring the full range of eth precompiles is always warmed up.
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/895)
=> fix: warm up 0x0a precompile

crates/evm/src/instructions/environmental_information.cairo
Resolves: #
- Fixes a bug where COPY opcodes would overflow/underflow in some combinations of size / offset / source_len
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/903)
=> fix: copy opcodes slices overflows

.tool-versions, Scarb.lock, crates/alexandria_data_structures/Scarb.toml, crates/contracts/Scarb.toml, crates/evm/Scarb.toml, crates/evm/src/precompiles.cairo, crates/evm/src/precompiles/ec_add.cairo, crates/evm/src/precompiles/ec_mul.cairo, crates/openzeppelin/Scarb.toml, crates/snforge_utils/Scarb.toml, crates/snforge_utils/src/lib.cairo, crates/utils/Scarb.toml
Resolves: #856
Wrap ecAdd / ecMul
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/880)
=> feat: ecAdd / ecMul

crates/evm/src/precompiles/p256verify.cairo, crates/utils/Scarb.toml, crates/utils/src/crypto/modexp/mpnat.cairo, crates/utils/src/helpers.cairo, crates/utils/src/rlp.cairo
Resolves: #
- Optimize function in FromBytes
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/907)
=> dev: optimize FromBytes

crates/contracts/src/account_contract.cairo, crates/contracts/tests/lib.cairo, crates/contracts/tests/test_execution_from_outside.cairo
Related to https://github.com/kkrt-labs/kakarot-ssj/issues/819.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/836)
=> feat: SNIP-9

crates/evm/src/instructions/system_operations.cairo
Resolves: #
- Fixes a double-charging of gas for CREATE2 (covered in prepare_create)
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/912)
=> fix CREATE2 gas

crates/evm/src/create_helpers.cairo, crates/evm/src/gas.cairo, crates/evm/src/instructions/environmental_information.cairo, crates/evm/src/instructions/logging_operations.cairo, crates/evm/src/instructions/memory_operations.cairo, crates/evm/src/instructions/sha3.cairo, crates/evm/src/instructions/system_operations.cairo, crates/evm/src/interpreter.cairo, crates/evm/src/memory.cairo, crates/evm/src/precompiles/ec_recover.cairo, crates/evm/src/precompiles/identity.cairo, crates/evm/src/precompiles/sha256.cairo, crates/evm/src/test_utils.cairo, scripts/gas_debug_call.py
Resolves: #910
Resolves: #911
- Fixes a bug where memory expansion was not always applied properly, as the max memory offset written could be different from the max theoritical memory offset passed in calls.
- As memory is always resized prior to calls / operations, removed length checks & expansions in the memory trait
- Fixes a bug where memory expansion was computed based on the max offset, even if the associated size written was zero.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/913)
=> fix: memory expansions

crates/evm/src/instructions/system_operations.cairo, crates/evm/src/stack.cairo
Resolves: #914
- Saturates the gas taken from the stack to MAX_U128 so that, if the gas is passed with a very big value, the execution doesn't throw an error here. The actual gas passed to the call will depend on the min(gas_left, gas_param), and since gas_left is a u128, it's safe to saturate 
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/915)
=> fix: saturate gas taken from stack

crates/contracts/src/account_contract.cairo, crates/contracts/tests/test_kakarot_core.cairo, crates/evm/src/backend/starknet_backend.cairo, crates/evm/src/instructions/block_information.cairo, crates/evm/src/instructions/environmental_information.cairo, crates/evm/src/instructions/memory_operations.cairo, crates/evm/src/instructions/system_operations.cairo, crates/evm/src/model/account.cairo, crates/evm/src/state.cairo
Resolves: #840
Code hash cache in storage
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/930)
=> feat: cache code_hash

crates/contracts/src/kakarot_core/kakarot.cairo, crates/contracts/tests/test_kakarot_core.cairo, crates/evm/src/backend/validation.cairo, crates/evm/src/instructions/memory_operations.cairo, crates/evm/src/instructions/system_operations.cairo, crates/utils/src/errors.cairo, crates/utils/src/eth_transaction.cairo, crates/utils/src/eth_transaction/eip1559.cairo, crates/utils/src/eth_transaction/eip2930.cairo, crates/utils/src/eth_transaction/transaction.cairo, crates/utils/src/rlp.cairo
Resolves: #
- Fixes an issue where Access Lists would only have their first member properly deserialized from the RLP encoding.
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/933)
=> fix: access list deserializing

crates/contracts/src/account_contract.cairo, crates/contracts/src/kakarot_core.cairo, crates/contracts/src/kakarot_core/eth_rpc.cairo, crates/contracts/src/kakarot_core/interface.cairo, crates/contracts/src/kakarot_core/kakarot.cairo, crates/contracts/tests/test_kakarot_core.cairo, crates/evm/src/instructions/system_operations.cairo, crates/evm/src/interpreter.cairo
Resolves: #
- Adds an `EthRPC` trait, the goal is to implement "regular ethRPC" methods like done in KakarotZero.
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/937)
=> refactor: add EthRPC trait

crates/evm/src/backend/validation.cairo
Resolves: #
- Writes a first test example for validate_eth_tx unit tests
- Other will need to be completed later.
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/946)
=> dev: write test template for validate_eth_tx

crates/evm/src/instructions/push_operations.cairo, crates/evm/src/model/vm.cairo
Resolves: #
- Fixes an issue where, if we did a `push_i` instruction, we might try to get a slice of bytecode that is out of bounds.
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/947)
=> fix: out-of-bounds read on push instructions

crates/evm/src/backend/validation.cairo, crates/evm/src/call_helpers.cairo, crates/evm/src/instructions/push_operations.cairo, crates/evm/src/instructions/stop_and_arithmetic_operations.cairo, crates/evm/src/instructions/system_operations.cairo, crates/evm/src/interpreter.cairo, crates/evm/src/model/vm.cairo, crates/utils/src/eth_transaction.cairo, crates/utils/src/helpers.cairo
Resolves: #
- Fixes an issue where the returndata buffer was not correctly emptied on stop.
- Fixes an issue where the returndata was copied in memory for exceptional halts.
- Adapted the CALL opcodes tests accordingly - no longer checking returndata, but rather checking the context in which an SSTORE was executed...
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/948)
=> fix: returndata buffer emptied on stop

crates/evm/src/create_helpers.cairo, crates/evm/src/errors.cairo, crates/evm/src/gas.cairo, crates/evm/src/instructions/environmental_information.cairo, crates/evm/src/instructions/logging_operations.cairo, crates/evm/src/instructions/memory_operations.cairo, crates/evm/src/instructions/sha3.cairo, crates/evm/src/instructions/system_operations.cairo
Resolves: #
- Fixes an issue where, given values high enough, offset + size could overflow
- Used a Result to manage this issue.
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/949)
=> fix: memory expansion cost could overflow

crates/evm/src/create_helpers.cairo, crates/evm/src/instructions/environmental_information.cairo, crates/evm/src/instructions/logging_operations.cairo, crates/evm/src/instructions/memory_operations.cairo, crates/evm/src/instructions/system_operations.cairo, crates/evm/src/stack.cairo
Resolves: #
- In some cases, it was possible that a memory offset taken from the stack was absurdely high, but combined with a null size. In this case, since no memory was modified, no gas was charged for that, and the memory was not resized
- This ensures that, for these high values, the program doesn't fail with a type execution error - rather, we saturate at the max_usize value, s.t. if size != 0, the memory expansion will create a failure because of a too high cost - and otherwise, the tx will pass.
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/950)
=> fix: saturate memory offset taken from stack

crates/contracts/src/kakarot_core/eth_rpc.cairo, crates/evm/src/backend/validation.cairo, crates/evm/src/interpreter.cairo, crates/utils/src/eth_transaction.cairo
Resolves: #
- Fixes an issue where effective gas price was not using the effective tip but the max tip possible
- Used the more logical `Transaction` function `get_effective_gas_price` instead of having a separate function
- Now the checks and the computation are done in different places.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/951)
=> fix: effective gas price

crates/evm/src/backend/starknet_backend.cairo, crates/snforge_utils/src/contracts.cairo, crates/snforge_utils/src/lib.cairo
Resolves: #
- Fixes an issue where, because account storage and account commitments are separate, we were skipping storage commits in case an account was SELFDESTRUCT instead of SELFDESTRUCT **and** created in the same tx.
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/953)
=> fix: storage commitment on selfdestruct accounts

crates/evm/src/instructions/system_operations.cairo
Resolves: #
- Fixes an issue where SELFDESTRUCT would not warmup the recipient address.
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/954)
=> fix: warmup recipient in selfdestruct

crates/evm/src/instructions/memory_operations.cairo, crates/evm/src/instructions/push_operations.cairo, crates/evm/src/interpreter.cairo, crates/evm/src/model/vm.cairo
Resolves: #
- Fixes an issue where PC should be incremented AFTER opcode execution, not before
- (skip increment for JUMP family opcodes)
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/955)
=> fix: increment pc post-opcode execution

crates/evm/src/backend/starknet_backend.cairo, crates/evm/src/instructions/environmental_information.cairo, crates/evm/src/instructions/memory_operations.cairo, crates/evm/src/interpreter.cairo, crates/evm/src/model.cairo, crates/evm/src/model/account.cairo, crates/evm/src/state.cairo, crates/evm/src/test_utils.cairo
- Fixes an issue where the nonce used was incremented before computing the target address in deploy transactions.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/957)
=> fix: origin nonce used in deploy tx & available balance in tx

crates/evm/src/precompiles/ec_recover.cairo, crates/utils/src/traits.cairo
Fixes the y_parity value in ec_recover and handling of point at infinity
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/958)
=> fix: ec_recover when point at infinity

crates/evm/src/backend/starknet_backend.cairo, crates/evm/src/errors.cairo, crates/evm/src/interpreter.cairo, crates/evm/src/model.cairo
Fixes an issue where the state returned in case of a create collision was the default, empty state instead of the one with the increased sender nonce.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/959)
=> fix: create collision state

crates/evm/src/precompiles/ec_add.cairo, crates/evm/src/precompiles/ec_mul.cairo
Ensures the length passed to the precompile inputs
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/960)
=> fix: ec_precompiles input padding

crates/evm/src/precompiles/ec_add.cairo, crates/evm/src/precompiles/ec_mul.cairo
Fixes computations of ec_add / ec_mul
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/961)
=> fix: ecadd/mul

crates/evm/src/errors.cairo, crates/evm/src/interpreter.cairo
Resolves: # 969
- ensure sender nonce doesnt overflow
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/974)
=> fix: create high nonce

.tool-versions
Decreases testing time by a huge margin with latest improvements in the compilation model of scarb and starknet-foundry.
Before: 
```
scarb test  508.48s user 79.38s system 174% cpu 5:37.26 total total
```
After
```
scarb test  363.00s user 64.87s system 181% cpu 3:55.85 
```
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/981)
=> dev: bump versions with test speedups

crates/contracts/src/storage.cairo, crates/evm/src/backend/starknet_backend.cairo, crates/evm/src/instructions/duplication_operations.cairo, crates/evm/src/instructions/environmental_information.cairo, crates/evm/src/instructions/push_operations.cairo, crates/evm/src/instructions/sha3.cairo, crates/evm/src/memory.cairo, crates/evm/src/precompiles.cairo, crates/evm/src/precompiles/blake2f.cairo, crates/evm/src/precompiles/ec_operations/ec_mul.cairo, crates/evm/src/stack.cairo, crates/evm/src/state.cairo, crates/snforge_utils/src/lib.cairo, crates/utils/src/crypto/blake2_compress.cairo, crates/utils/src/eth_transaction/eip2930.cairo, crates/utils/src/felt_vec.cairo, crates/utils/src/helpers.cairo, crates/utils/src/rlp.cairo, crates/utils/src/serialization.cairo, crates/utils/src/traits.cairo, crates/utils/src/traits/array.cairo, crates/utils/src/traits/bytes.cairo, crates/utils/src/traits/eth_address.cairo, crates/utils/src/traits/integer.cairo
Replace while loops to use the new for loops
Resolves: #978 
- Replacement of while loops with for loops
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/987)
=> refactor: replace `while` loops with `for`

crates/evm/src/create_helpers.cairo, crates/evm/src/gas.cairo, crates/evm/src/instructions/environmental_information.cairo, crates/evm/src/instructions/memory_operations.cairo, crates/evm/src/instructions/sha3.cairo, crates/utils/src/helpers.cairo
Resolves: #940 
- Introduces new function `bytes_32_words_size` which return number of 32 byte words required to represent `size`
- Replaces the `ceil32` function with `bytes_32_word_size` wherever applicable.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/985)
=> Optimizes conversion of bytes to words

crates/evm/src/instructions/environmental_information.cairo, crates/evm/src/instructions/system_operations.cairo, crates/evm/src/memory.cairo, crates/evm/src/precompiles/ec_operations/ec_add.cairo, crates/evm/src/precompiles/ec_operations/ec_mul.cairo, crates/utils/src/helpers.cairo
Resolves: #906 
- Removes the use of `load_word` in the codebase.
- Uses `from_be_bytes` and `from_be_bytes_partial` instead for same functionality.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/988)
=> refactor: remove `load_word` in favor of `FromBytes`

crates/contracts/src/kakarot_core/eth_rpc.cairo, crates/contracts/src/kakarot_core/interface.cairo, crates/contracts/src/kakarot_core/kakarot.cairo, crates/evm/src/backend/starknet_backend.cairo, crates/evm/src/backend/validation.cairo
This PR implements `eth_get_balance` and use it instead of querying the balanceOf function of the `native_token` in the codebase. It also fixes a suspected bug in `get_starknet_address` from `KakarotCore`.
The `eth_get_balance` is not implemented and thus we need to query the `native_token` directly in several parts of the codebase.
Resolves: #941 
The `eth_get_balance` is now implemented and replicates its `eth_getBalance` counterpart in the EVM.
- The implementation of `eth_get_balance` leverages the `get_starknet_address` function from `KakarotCore` to get the corresponding starknet address from an evm address. Once we have the underlying starknet address, we query the `native_token` balance. The function has also been added to …
=> Implement eth_get_balance

crates/evm/src/backend/validation.cairo, crates/evm/src/create_helpers.cairo, crates/evm/src/instructions/system_operations.cairo, crates/evm/src/interpreter.cairo
fix: add a validation check on sender nonce to avoid an un-documented overflow
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/995)
=> fix: create tx nonce overflow

.gitignore, Makefile, crates/evm/src/backend/starknet_backend.cairo, scripts/filter_tests.py, scripts/run_filtered_tests.py
Adds compile-time filtering to run unit tests.
usage:
`make test-unit <package_name> <filter_to_apply>`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/997)
=> dev: implement compile-time filtering for tests

crates/contracts/src/kakarot_core/eth_rpc.cairo, crates/contracts/src/kakarot_core/interface.cairo, crates/evm/src/backend/validation.cairo
This PR include changes on the following file `crates/contracts/src/kakarot_core/eth_rpc.cairo`. I'm doing the implementation of the eth_get_transaction_count function. The issue is not done yet.
Normal
Resolves: #942 
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/983)
=> Implementation of eth_get_transaction_count function

crates/evm/src/gas.cairo, crates/evm/src/instructions/system_operations.cairo
Fixes an eventual overflow in `message_call_gas`
https://github.com/kkrt-labs/kakarot-ssj/issues/965
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/996)
=> fix: overflow in message_call_gas

crates/contracts/src/cairo1_helpers.cairo, crates/contracts/src/kakarot_core/interface.cairo, crates/evm/src/call_helpers.cairo, crates/evm/src/interpreter.cairo, docs/general/contract_storage.md
fix: typos
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/1000)
=> fix: typos

crates/contracts/src/kakarot_core/eth_rpc.cairo, crates/evm/src/instructions/memory_operations.cairo
Saturates the jumpi index taken on the stack to avoid returning directly if it doesn't fit in a usize. 
If b is zero, it will just increment PC. 
Otherwise, it will be OOB of the bytecode which is capped to 24kb, thus at an invalid jumpdest index.
Closes #971
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/1002)
=> fix: saturate jumpi index taken on stack

crates/evm/src/create_helpers.cairo, crates/evm/src/instructions/block_information.cairo, crates/evm/src/instructions/environmental_information.cairo, crates/evm/src/instructions/logging_operations.cairo, crates/evm/src/instructions/memory_operations.cairo, crates/evm/src/instructions/sha3.cairo, crates/evm/src/instructions/system_operations.cairo, crates/evm/src/interpreter.cairo, crates/evm/src/stack.cairo
fixes some type conversion issues when executing opcode. adding some comments for clarity.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/1005)
=> fix: conversion of stack values in opcode execution

crates/contracts/tests/test_kakarot_core.cairo, crates/evm/src/create_helpers.cairo, crates/evm/src/gas.cairo, crates/evm/src/instructions/duplication_operations.cairo, crates/evm/src/instructions/environmental_information.cairo, crates/evm/src/instructions/logging_operations.cairo, crates/evm/src/instructions/memory_operations.cairo, crates/evm/src/instructions/sha3.cairo, crates/evm/src/instructions/stop_and_arithmetic_operations.cairo, crates/evm/src/instructions/system_operations.cairo, crates/evm/src/interpreter.cairo, crates/evm/src/precompiles/identity.cairo, crates/evm/src/precompiles/p256verify.cairo, crates/evm/src/precompiles/sha256.cairo, crates/utils/src/helpers.cairo, scripts/setup_cairo_native.sh
Unit test of the KakarotCore::get_starknet_address function
Function not tested.
Resolves: #991 
Function tested with full coverage of the 2 possible outcomes.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/1006)
=> test: get_starknet_address

crates/evm/src/backend/starknet_backend.cairo, crates/evm/src/model.cairo, crates/snforge_utils/src/lib.cairo
This PR implements the unit test for the emit_events function.
The emit_events function doesn't have any unit tests.
Resolves: #952 
-  The test_emit_events function generates some events and adds them to the state before calling the emit_events function. This allows the events to be asserted using the spy.assert_emitted function.
-  I created a MockEvent struct to implement the event trait, as the append_keys_and_data function is required for the assert_emitted function to work. Without that implementation, attempts to assert the events would fail because the expected events in the comparison were empty.
- I added a helper function to serialize mock events to match the structure of the emitted events, so they can be properly asserted.
- …
=> dev: test emit_events

crates/utils/src/eth_transaction/legacy.cairo, crates/utils/src/eth_transaction/transaction.cairo
Refactor `decode_legacy_tx` for consistency with typed transactions
- Step 1: Decodes `encoded_tx_data` and returns the decoded data.
- Step 2: Implements a trait in `crates/utils/src/eth_transaction/transaction.cairo` to decode transaction fields.
Resolves: #979 
- Decodes transaction
- Trait to decode transaction fields
- Consistency with typed transactions `eip2930.cairo`
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/1012)
=> refactor: `decode_legacy_tx` for consistency with typed transactions

crates/contracts/src/kakarot_core/kakarot.cairo, crates/contracts/src/test_utils.cairo, crates/contracts/tests/test_execution_from_outside.cairo, crates/contracts/tests/test_kakarot_core.cairo
Resolves: #936
-
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/1017)
=> feat: enable registration checks

crates/contracts/src/account_contract.cairo, crates/contracts/src/kakarot_core/eth_rpc.cairo, crates/contracts/src/kakarot_core/interface.cairo, crates/contracts/tests/test_execution_from_outside.cairo, crates/contracts/tests/test_kakarot_core.cairo, crates/utils/src/eth_transaction/transaction.cairo, crates/utils/src/traits/bytes.cairo
Closes #943
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/1015)
=> refactor: eth_send_raw_transaction

crates/contracts/src/kakarot_core/eth_rpc.cairo, crates/contracts/src/kakarot_core/interface.cairo, crates/contracts/src/kakarot_core/kakarot.cairo, crates/contracts/tests/test_execution_from_outside.cairo, crates/contracts/tests/test_kakarot_core.cairo, crates/evm/src/backend/starknet_backend.cairo, crates/evm/src/call_helpers.cairo, crates/evm/src/interpreter.cairo, crates/evm/src/model/account.cairo
Resolves: #1016 
Resolves: #928
- Ensure only a Kakarot account can send transactions on behalf of an EVM address
-
-
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/1018)
=> feat: safe get evm address

crates/utils/src/math.cairo
Fixes Exponentiation::pow [KGA-3] [KGA-122]
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kkrt-labs/kakarot-ssj/1022)
=> [KGA-3] [KGA-122] fix: SSJ pow

crates/contracts/src/cairo1_helpers.cairo
required for https://github.com/kkrt-labs/kakarot/pull/1625
=> [KGA-19] feat: add new_call_contract_syscall to Cairo1Helpers class

docs/CONTRIBUTING.md, docs/general/contract_storage.md
This pull request contains changes to improve clarity, correctness and structure.
Description correction:
A space has been added to the sentence and corrected `account` to `accounts`
Please review the changes and let me know if any additional changes are needed.
=> fix: typos in documentation files
